#Sin este archivo, si el usuario va directo a http://localhost/dashboard nginx devuelve 404 
#porque no existe ese archivo físico. Con try_files siempre sirve el index.html 
#y Angular Router maneja el resto.

server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Redirigir todas las rutas al index.html (necesario para Angular Router)
    location / {
        try_files $uri $uri/ /index.html;
    }
}